// scripts/generate_alert_codes.mjs
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const IN_PATH = path.join(ROOT, "constants", "alert_codes.json");
const OUT_TS = path.join(ROOT, "constants", "alert_codes.ts");
const OUT_JS = path.join(ROOT, "constants", "alert_codes.js");

function fail(msg) {
  console.error(`ERROR: ${msg}`);
  process.exit(1);
}

function readJson(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf8"));
  } catch (e) {
    fail(`Failed to parse JSON at ${filePath}: ${e.message}`);
  }
}

function assertRegistryShape(reg) {
  if (!reg || typeof reg !== "object") fail("Registry root must be an object.");
  if (!reg.codes || typeof reg.codes !== "object") fail("Registry must have a top-level 'codes' object.");

  const codes = Object.keys(reg.codes);
  if (codes.length === 0) fail("Registry 'codes' is empty.");

  for (const code of codes) {
    if (typeof code !== "string" || !code.trim()) fail("Found empty/invalid code key in registry.");
    if (!/^[A-Z0-9_]+$/.test(code)) {
      fail(`Invalid code '${code}'. Only A-Z, 0-9, underscore allowed.`);
    }

    const meta = reg.codes[code];
    if (!meta || typeof meta !== "object") fail(`Code '${code}' metadata must be an object.`);
    if (!meta.domain || typeof meta.domain !== "string") fail(`Code '${code}' missing 'domain' string.`);
    if (!meta.default_severity || typeof meta.default_severity !== "string") {
      fail(`Code '${code}' missing 'default_severity' string.`);
    }
  }
}

function stableSortKeys(obj) {
  return Object.fromEntries(Object.keys(obj).sort().map(k => [k, obj[k]]));
}

function emitTS(reg) {
  const codes = stableSortKeys(reg.codes);
  const codeUnion = Object.keys(codes).map(c => `"${c}"`).join(" | ");
  const domains = [...new Set(Object.values(codes).map(v => v.domain))].sort();
  const severities = [...new Set(Object.values(codes).map(v => v.default_severity))].sort();
  const domainUnion = domains.map(d => `"${d}"`).join(" | ");
  const severityUnion = severities.map(s => `"${s}"`).join(" | ");

  const lines = [];
  lines.push(`/* AUTO-GENERATED FILE. DO NOT EDIT.\n * Source: constants/alert_codes.json\n * Generated by: scripts/generate_alert_codes.mjs\n */\n`);
  lines.push(`export type AlertCode = ${codeUnion};`);
  lines.push(`export type AlertDomain = ${domainUnion};`);
  lines.push(`export type AlertDefaultSeverity = ${severityUnion};\n`);
  lines.push(`export const ALERT_CODES = Object.freeze({`);
  for (const code of Object.keys(codes)) {
    lines.push(`  ${code}: "${code}",`);
  }
  lines.push(`} as const);\n`);
  lines.push(`export const ALERT_CODE_META: Record<AlertCode, { domain: AlertDomain; default_severity: AlertDefaultSeverity }> = Object.freeze({`);
  for (const [code, meta] of Object.entries(codes)) {
    lines.push(`  "${code}": { domain: "${meta.domain}", default_severity: "${meta.default_severity}" },`);
  }
  lines.push(`});\n`);
  lines.push(`export function isRegisteredAlertCode(x: unknown): x is AlertCode {`);
  lines.push(`  return typeof x === "string" && Object.prototype.hasOwnProperty.call(ALERT_CODE_META, x);`);
  lines.push(`}\n`);
  return lines.join("\n");
}

function emitJS(reg) {
  const codes = stableSortKeys(reg.codes);
  const lines = [];
  lines.push(`/* AUTO-GENERATED FILE. DO NOT EDIT.\n * Source: constants/alert_codes.json\n * Generated by: scripts/generate_alert_codes.mjs\n */\n`);
  lines.push(`const ALERT_CODES = Object.freeze({`);
  for (const code of Object.keys(codes)) {
    lines.push(`  ${code}: "${code}",`);
  }
  lines.push(`});\n`);
  lines.push(`const ALERT_CODE_META = Object.freeze({`);
  for (const [code, meta] of Object.entries(codes)) {
    lines.push(`  "${code}": { domain: "${meta.domain}", default_severity: "${meta.default_severity}" },`);
  }
  lines.push(`});\n`);
  lines.push(`function isRegisteredAlertCode(x) {`);
  lines.push(`  return typeof x === "string" && Object.prototype.hasOwnProperty.call(ALERT_CODE_META, x);`);
  lines.push(`}\n`);
  lines.push(`module.exports = { ALERT_CODES, ALERT_CODE_META, isRegisteredAlertCode };`);
  return lines.join("\n");
}

(function main() {
  if (!fs.existsSync(IN_PATH)) fail(`Missing ${IN_PATH}`);
  const reg = readJson(IN_PATH);
  assertRegistryShape(reg);
  fs.mkdirSync(path.dirname(OUT_TS), { recursive: true });
  fs.mkdirSync(path.dirname(OUT_JS), { recursive: true });
  fs.writeFileSync(OUT_TS, emitTS(reg), "utf8");
  fs.writeFileSync(OUT_JS, emitJS(reg), "utf8");
  console.log(`Generated:\n- ${path.relative(ROOT, OUT_TS)}\n- ${path.relative(ROOT, OUT_JS)}`);
})();
